<?php
return [
'modularList'=>[
'addModular'=>'<a href="/Index/Auth/addModular" class=""><i class="fa fa-plus"></i> 新增模块</a>',
'editModular'=>'<a href="/Index/Auth/editModular" class="a_list c_1785c8 m_r_10 edit"><i class="fa fa-pencil-square"></i> 修改模块</a>',
'delModular'=>'<a href="/Index/Auth/delModular" class="a_list c_1785c8 del"><i class="fa fa-times-circle"></i> 删除模块</a>',
'modularDelList'=>'<a href="/Index/Auth/modularDelList" class="a_del"><i class="fa fa-trash-o"></i> 回收站</a>',
'useModular'=>'<a href="javascript:void(0);" class="status b_28b5d6 C_FFF useModular">启用</a>',
'purgeModular'=>'<a href="javascript:void(0);" class="a_list c_1785c8 purge"><i class="fa fa-times-circle"></i></a>',
],
'authsList'=>[
'addAuth'=>'<a href="/Index/Auth/addAuth" class=""><i class="fa fa-plus"></i> 新增权限</a>',
'editAuth'=>'<a href="javascript:void(0);" class="a_list c_1785c8 m_r_10 edit"><i class="fa fa-pencil-square"></i></a>',
'delAuth'=>'<a href="javascript:void(0);" class="a_list c_1785c8 del"><i class="fa fa-times-circle"></i></a>',
'authDelList'=>'<a href="/Index/Auth/authDelList" class="a_del"><i class="fa fa-trash-o"></i> 回收站</a>',
'useAuth'=>'<a href="javascript:void(0);" class="status b_28b5d6 C_FFF useAuth">启用</a>',
'purgeAuth'=>'<a href="/Index/Auth/purgeAuth" class="a_list c_1785c8 purge"><i class="fa fa-times-circle"></i></a>',
],
'top'=>[
'goodsServer'=>'<a href="/Index/Top/goodsServer" class="">商品与服务 <i class="fa fa-caret-down"></i></a>',
'search'=>'<a href="/Index/Top/search" class="">搜索</a>',
'workOrder'=>'<a href="/Index/Top/workOrder" class="">工单服务</a>',
'help'=>'<a href="/Index/Top/help" class="">帮助与文档</a>',
],
'goodsList'=>[
'delGoods'=>'<a href="javascript:void(0);" class="delGoods"><i class="fa fa-times-circle"></i> 删除商品</a>',
'goodsDelList'=>'<a href="/Index/Goods/goodsDelList" class="a_del"><i class="fa fa-trash-o"></i> 回收站</a>',
'addGoods'=>'<a href="/Index/Goods/addGoods" class=""><i class="fa fa-plus"></i> 添加商品</a>',
'addGoodsSKU'=>'<a href="javascript:void(0);" class="a_list c_28b5d6"><i class="fa fa-clipboard"></i></a>',
'editGoods'=>'<a href="javascript:void(0);" class="a_list c_1785c8"><i class="fa fa-pencil-square"></i></a>',
'goodsImport'=>'<a href="/Index/Goods/goodsImport" class=""><i class="fa fa-sign-in fa-rotate-90"></i> 商品批量导入</a>',
],
'userList'=>[
'addUser'=>'<a href="/Index/Ucenter/addUser" class=""><i class="fa fa-plus"></i> 新增员工</a>',
'editUser'=>'<a href="javascript:void(0);" class="a_list c_1785c8 m_r_10 edit"><i class="fa fa-pencil-square"></i></a>',
'delUser'=>'<a href="javascript:void(0);" class="a_list c_1785c8 del"><i class="fa fa-times-circle"></i></a>',
'userDelList'=>'<a href="/Index/Ucenter/userDelList" class="a_del"><i class="fa fa-trash-o"></i> 回收站</a>',
'useUser'=>'<a href="javascript:void(0);" class="status b_28b5d6 C_FFF useUser">启用</a>',
'purgeUser'=>'<a href="javascript:void(0);" class="a_list c_1785c8 purge"><i class="fa fa-times-circle"></i></a>',
],
'roleList'=>[
'addRole'=>'<a href="/Index/Ucenter/addRole" class=""><i class="fa fa-plus"></i> 新增组织</a>',
'editRole'=>'<a href="/Index/Ucenter/editRole" class="a_list c_1785c8 m_r_10 edit"><i class="fa fa-pencil-square"></i></a>',
'delRole'=>'<a href="/Index/Ucenter/delRole" class="a_list c_1785c8 del"><i class="fa fa-times-circle"></i></a>',
'roleDelList'=>'<a href="/Index/Ucenter/roleDelList" class="a_del"><i class="fa fa-trash-o"></i> 回收站</a>',
'useRole'=>'<a href="javascript:void(0);" class="status b_28b5d6 C_FFF useRole">启用</a>',
'purgeRole'=>'<a href="javascript:void(0);" class="a_list c_1785c8 purge"><i class="fa fa-times-circle"></i></a>',
],
'myUser'=>[
'editMyUser'=>'<a href="javascript:void(0);" class="submit">保存</a>',
],
'category'=>[
'addCategory'=>'<a href="/Index/Goods/addCategory" class=""><i class="fa fa-plus"></i> 添加分类</a>',
'delCategory'=>'<a href="javascript:void(0);" class="a_list c_1785c8 remove_status"><i class="fa fa-times-circle-o"></i></a>',
],
'selfWarehouse'=>[
'selfDelList'=>'<a href="/Index/Warehouse/selfDelList" class="a_del"><i class="fa fa-trash-o"></i> 回收站</a>',
'addSelfWarehouse'=>'<a href="/Index/Warehouse/addSelfWarehouse" class=""><i class="fa fa-plus"></i> 新增自营仓库</a>',
'editSelfWarehouse'=>'<a href="javascript:void(0);" class="a_list c_1785c8 selfWarehouse"><i class="fa fa-pencil-square"></i></a>',
'goodsShelvesList'=>'<a href="javascript:void(0);" class="a_list c_28b5d6 selfStorage"><i class="fa fa-list-ul"></i></a>',
'addStorage'=>'<a href="javascript:void(0);" class="addStorage"><i class="fa fa-plus"></i> 添加货架</a>',
'editStorage'=>'<a href="javascript:void(0);" class="a_list c_1785c8 editStorage"><i class="fa fa-pencil-square"></i></a>',
'storageDelList'=>'<a href="/Index/Warehouse/storageDelList" class="a_del"><i class="fa fa-trash-o"></i> 货架回收站</a>',
'delStorage'=>'<a href="javascript:void(0);" class="delStorage"><i class="fa fa-times-circle-o"></i> 禁用</a>',
],
'goodsBrand'=>[
'addGoodsBrand'=>'<a href="/Index/Goods/addGoodsBrand" class=""><i class="fa fa-plus"></i> 添加品牌</a>',
'delGoodsBrand'=>'<a href="javascript:void(0);" class="delGoodsBrand"><i class="fa fa-times-circle-o"></i> 删除品牌</a>',
'editGoodsBrand'=>'<a href="javascript:void(0);" class="editGoodsBrand"><i class="fa fa-pencil-square"></i></a>',
],
'goodsSKU'=>[
'addGoodsSKU'=>'<a href="/Index/Goods/addGoodsSKU" class=""><i class="fa fa-plus"></i> 添加sku</a>',
'editSku'=>'<a href="javascript:void(0)" class="a_list c_1785c8 editGoodsSKU"><i class="fa fa-pencil-square"></i></a>',
'delGoodsSKU'=>'<a href="javascript:void(0);" class="delGoodsSKU"><i class="fa fa-times-circle-o"></i> 删除SKU</a>',
],
'inwarehouse'=>[
'editInware'=>'<a href="javascript:void(0);" class="a_list c_1785c8 editInware"><i class="fa fa-pencil-square"></i></a>',
'addBatch'=>'<a href="javascript:void(0);" class="a_list c_1785c8 addBatch"><i class="fa fa-sliders"></i></a>',
'batchList'=>'<a href="javascript:void(0);" class="a_list c_999 batchList"><i class="fa fa-table"></i></a>',
'addInware'=>'<a href="/Index/Declaration/addInware" class=""><i class="fa fa-plus"></i> 新增入仓单</a>',
'inwareDelList'=>'<a href="/Index/Declaration/inwareDelList" class="a_del"><i class="fa fa-trash-o"></i> 回收站</a>',
],
'thirdWarehouse'=>[
'addThirdWarehouse'=>'<a href="/Index/Warehouse/addThirdWarehouse" class=""><i class="fa fa-plus"></i> 新增第三方仓库</a>',
'editThirdWarehouse'=>'<a href="javascript:void(0);" class="a_list c_1785c8 thirdWarehouse"><i class="fa fa-pencil-square"></i></a>',
'thirdDelList'=>'<a href="/Index/Warehouse/thirdDelList" class="a_del"><i class="fa fa-trash-o"></i> 回收站</a>',
],
'batch'=>[
'addBatch'=>'<a href="/Index/Declaration/addBatch" class=""><i class="fa fa-plus"></i> 新增批次</a>',
'editBatch'=>'<a href="javascript:void(0);" class="a_list c_1785c8 m_r_10 edit"><i class="fa fa-pencil-square"></i></a>',
'delBatch'=>'<a href="javascript:void(0);" class="a_list c_1785c8 del"><i class="fa fa-times-circle"></i></a>',
'onStock'=>'<a href="javascript:void(0);" class="a_c_1785c8 onStock">去上架</a>',
'batchDelList'=>'<a href="/Index/Declaration/batchDelList" class="a_del"><i class="fa fa-trash-o"></i> 回收站</a>',
],
'goodsBoom'=>[
'addGoodsBoom'=>'<a href="/Index/Goods/addGoodsBoom" class=""><i class="fa fa-plus"></i> 新增Boom</a>',
'delGoodsBoom'=>'<a href="javascript:void(0);" class="delGoodsBoom"><i class="fa fa-times-circle-o"></i> 删除Boom</a>',
],
'dealerList'=>[
'addDealer'=>'<a href="/Index/Dealer/addDealer" class=""><i class="fa fa-plus"></i> 添加客户</a>',
'addBlack'=>'<a href="javascript:void(0);" class="addBlack"><i class="fa fa-times-circle-o"></i> 加入黑名单</a>',
'editDealer'=>'<a href="javascript:void(0);" class="a_list c_1785c8 editDealer"><i class="fa fa-search"></i></a>',
'blackList'=>'<a href="/Index/Dealer/blackList" class="a_del"><i class="fa fa-trash-o"></i> 回收站</a>',
],
'supplierList'=>[
'editSupplier'=>'<a href="javascript:void(0);" class="a_list c_1785c8 editSupplier"><i class="fa fa-search"></i></a>',
'addSupplier'=>'<a href="/Index/Supplier/addSupplier" class=""><i class="fa fa-plus"></i> 添加供应商</a>',
'addSupBlack'=>'<a href="javascript:void(0);" class="addBlack"><i class="fa fa-times-circle-o"></i> 加入黑名单</a>',
'supBlackList'=>'<a href="/Index/Supplier/supBlackList" class="a_del"><i class="fa fa-trash-o"></i> 回收站</a>',
],
];